language: objective-c

script:
    - cd "exampleProjects/IncrementalStore"
    # 32-bit tests
    - xctool -sdk iphonesimulator -scheme "Incremental Store Demo" clean test -destination "name=iPhone Retina (4-inch)"
    # 64-bit tests
    - xctool -sdk iphonesimulator -scheme "Incremental Store Demo" clean test -destination "name=iPhone Retina (4-inch 64-bit)"

before_install: 
  - brew update
  - brew unlink xctool
  - brew install xctool
  - export CC=gcc-4.8
